public class ArthimaticCalculations {
    public Integer addition(Integer x,Integer y) {
        Integer z=x+y;
        return z;
    }
    public Integer subtraction(Integer x, Integer y){
        Integer z=x-y;
        return z;
    }
    public Integer multiplication(Integer x, Integer y,Integer w){
        Integer z=x*y*w;
        return z;
    }
    public string concatStrings(string a, string b){
        string z=a + ' & ' + b;
        return z;
    }
}