public class CheckDatatypes {
    public void  methodBoolean() {
       boolean checkBoolean = true;
       System.debug(checkBoolean);
    }
    public void methodInteger(){
        integer varFirst = 1;
        integer varSecond = 2;
        System.debug(varFirst);
        System.debug(varSecond);
    }
    public void stringMethod(){
        string varname= 'name';
        string var2name='your name';
        
        system.debug(varname);
        system.debug(var2name);
    }
}
